[package]
name = "shadow_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
byteorder = "1"
wry = { version = "0.40", default-features = true, features = ["devtools"] }
tao = "0.26"
url = "2"

